### ISSUE TITLE
Pretrained model link is not working

### ISSUE THREAD

**Issue by sulunemre** [Giphy/celeb-detection-oss#11]
> Before running these examples you need to ensure that you downloaded the latest archive with Giphy pretrained models (resources)

`download_model.py` script tries to download this link but it returns 404:

https://s3.amazonaws.com/giphy-public/models/celeb-detection/resources.tar.gz

**Comment by dvoitekh** [comment]
@sulunemre sorry for late response. it should be working right now

**Comment by sulunemre** [comment]
Thanks!

**Comment by scottjg** [comment]
sadly they seem to have gone offline again. (now 403)

any chance someone has a copy?
